### ISSUE TITLE
Method to use to grab bot stats

### ISSUE THREAD

**Issue by ToasterSticks** [MrGriefs/discord.js-cluster#14]
Hey, to accumulate all bot guilds, would I use `client.cluster.fetchClientValues`, or `client.shard.fetchClientValues`

**Comment by MrGriefs** [comment]
`client.cluster.fetchClientValues` would be the appropriate method.

**Comment by ToasterSticks** [comment]
Thanks for the quick response! And if I wanted to reload commands that existed on the client, eg. `client.cache.commands` should I broadcastEval over shards or clusters?

**Comment by MrGriefs** [comment]
If you eval it over the shard, it would only affect all shards that cluster owns.  
If you eval it over the cluster, it would affect all clusters running.

**Comment by ToasterSticks** [comment]
Correct me if I'm wrong, but I thought `client.cluster.broadcastEval` runs a script over all clusters, just like how the sharding manager works. If that is the case, cluster should affect all shards of the bot which is what I'm looking for :)

**Comment by MrGriefs** [comment]
That is correct, edited my previous post.

**Comment by ToasterSticks** [comment]
Ah ok, that's what I needed. Clusters contain shards, and the sharding manager looks like it's  inherited from djs. No wonder client.shard.broadcastEval was hanging (at least they fixed it now)
