### ISSUE TITLE
Threading logic

### ISSUE THREAD

**Issue by ToasterSticks** [MrGriefs/discord.js-cluster#15]
Hey there, now that I've thought about it, how are threads distributed across the machine? Are there multiple processes per cpu core, and do threads share the same process id?  This would be useful in calculating and reducing ram usage into a single value since I'd need to know if I should filter out duplicate process ids. Thanks in advance.

**Comment by MrGriefs** [comment]
For example, if you have a server with 8 cores:
- 8 processes will get created and assigned to an individual core and take responsibilities of children
- Each of these cluster manager processes will fork 1 (one) sharding manager to take responsibilities of shards
- Sharding managers do not spawn processes, and are managed by the cluster manager for evals, shutdowns & restarts

**Comment by ToasterSticks** [comment]
Alright, so based on this I should filter when reducing with broadcastEval since multiple clients will occupy the same process. Unless there is another method that would be better for this 😄 

Also, the atop is for the threading option on the ClusterManager, correct?

**Comment by MrGriefs** [comment]
The `mode` option in the docs should answer your question
https://mrgriefs.github.io/discord.js-cluster/#/docs/main/main/typedef/ClusterManagerOptions
