### ISSUE TITLE
delayFor is not a function

### ISSUE THREAD

**Issue by igorwastaken** [MrGriefs/discord.js-cluster#29]
I put "GuildsperShard" and now the error "delayFor is not a function"

 https://github.com/MrGriefs/discord.js-cluster/blob/main/src/sharding/ClusterManager.js

**Comment by MrGriefs** [comment]
Can you elaborate on this issue please?

**Comment by igorwastaken** [comment]
bruh, I had forgotten to put ```{totalShards:"auto"}```
